### ISSUE TITLE
Could not load type 'Patcher.Program+<>c__DisplayClass2_0'

### ISSUE THREAD

**Issue by MostHated** [aevitas/unity-patch#1]
Hello, 
    I tried to run this and got the following error:
```shell
user@user-MS-7B79:~/Downloads/unity-patch-1.0-linux-x64$ mono Patcher.dll t=dark e=/home/user/Unity/Hub/Editor/2019.1.0f1/Editor/Unity

Unhandled Exception:
System.TypeLoadException: Could not load type 'Patcher.Program+<>c__DisplayClass2_0' from assembly 'Patcher, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Thanks,
-MH

**Comment by aevitas** [comment]
That's curious, what operating system were you running this on? 

Edit: I've just drafted a new release for the latest Unity, can you give that a go and see if you still run in to the same problem?

**Comment by aevitas** [comment]
Closing this because it's been quite a while since the last reply. If you're still running into this issue, feel free to re-open.
