### ISSUE TITLE
Does not work!

### ISSUE THREAD

**Issue by DrewRidley** [aevitas/unity-patch#10]
Does not work for unity 2019.3 beta.
`[drew@Drew-Desktop linux-x64]$ sudo ./Patcher -e=/opt/UnityBeta/Editor/Unity -t=dark -linux
Opening Unity executable from /opt/UnityBeta/Editor/Unity...
Creating backup..
Backup file created.. looks awake.
Searching for theme offset..
Could not find the theme offset in the specified executable.
[drew@Drew-Desktop linux-x64]$ 
`

Quite simply, it does not find the theme in the latest unity version!

**Comment by LinuxPleasure** [comment]
Yup, neither 2019.3 0f3, but I don't care to be out dated if Imma have the dark mode :P

**Comment by aevitas** [comment]
I hadn't updated the patcher for 2019.3 yet - I'll have a look and add more robust support for version switches.

**Comment by stychu** [comment]
@aevitas how is it going for 2019.3 0f3 and future ones ?

**Comment by aevitas** [comment]
@stychu I've just committed the OS specific version switches, working on finding the new patterns next.

**Comment by oliverbooth** [comment]
It's worth noting that in 2019.3, the theme bytes are swapped. Set flag `--theme=light` instead of `--theme=dark`, and you'll get the dark theme.

Edit: I just realised this issue was regarding Linux, and I'm on Windows. It may differ so my apologies

**Comment by aevitas** [comment]
Oh God this is going to haunt me forever. Let me fix that.

**Comment by aevitas** [comment]
Closing this as it has been a while since this issue has seen any discussion. Feel free to re-open it if the issue persists.
