### ISSUE TITLE
Theme offset not found

### ISSUE THREAD

**Issue by MichaelGatesDev** [aevitas/unity-patch#12]
**Description**
Could not find the theme offset in the specified executable.

**Version Information**
* What Operating System are you running the patcher on?
Manjaro KDE 5.17.5
* What Unity Version are you using?
2019.2.19f1

**Diagnostics**
What does the patcher output instead of the expected behaviour?
```
Version not explicitly specified -- defaulting to version 2019.2.3f1 for windows
Opening Unity executable from /opt/unity/editors/2019.2.19f1/Editor/Unity...
Creating backup..
Searching for theme offset..
Could not find the theme offset in the specified executable.
```

**Arguments**
`./Patcher -e=/opt/unity/editors/2019.2.19f1/Editor/Unity -t=dark -linux`

**Binaries**
If possible, provide a link to the Unity binary that corresponds with the version and OS you're using.

N/A

**Comment by aevitas** [comment]
Thanks for reporting this bug. I've committed a fix just a few minutes ago, and I'll put up a release that addresses this issue shortly.

**Comment by aevitas** [comment]
Release just went up after a small delay, can you check if it works now?

**Comment by cristianosucci** [comment]
It got the same error. I tried some minutes ago with the latest version. I'm using Unity _2019.3.2f1_ on _Ubuntu 18.04.4_.
```
➜  Patcher -e=Unity -t=dark -v=2019.3.2f1 -linux
Could not find patch details for linux Unity version 2019.3.2f1 -- defaulting to version 2019.2.3f.
Opening Unity executable from Unity...
Creating backup...
Searching for theme offset...
Error: Could not find the theme offset in the specified executable!
```
Is Unity 2019.3.2f1 on Linux supported?

**Comment by aevitas** [comment]
> Is Unity 2019.3.2f1 on Linux supported?

Not at the moment, I'd have to grab the 2019.3 binary from Linux and analyze it. I don't usually work with Linux, hence it lagging behind a little.

**Comment by Haywire-dev** [comment]
> Not at the moment, I'd have to grab the 2019.3 binary from Linux and analyze it. I don't usually work with Linux, hence it lagging behind a little.

Hello, I am looking forward for the compatibility of 2019.3* Linux version with your tool, as I actively use Linux. If I can help in any way fill me in with details, I have been trying several methods on my own but I don't think I had the right tools unfortunately.

**Comment by luna-skye** [comment]
I'm just moving from Win10 to Linux (KDE Neon 5.18), used to manually patching the executable myself and was glad to see this existed, but am trying to patch 2019.3.

I'd love to help anyway that I can to get this build supported :)

**Comment by thibault-duforest** [comment]
Hello, thank you for creating and updating this patch !

I'm running the latest 2020 beta version (currently 2020.1.0b4) and theme offset was not found. Is 2020.1 pattern supposed to work for minor version too ?
Is there a way for me to find it manually inside the EXE (in order to not bother you again with future updates!) or do I have to wait for you to update your program ?

**Comment by luna-skye** [comment]
> Hello, thank you for creating and updating this patch !
> 
> I'm running the latest 2020 beta version (currently 2020.1.0b4) and theme offset was not found. Is 2020.1 pattern supposed to work for minor version too ?
> Is there a way for me to find it manually inside the EXE (in order to not bother you again with future updates!) or do I have to wait for you to update your program ?

Might want to bring this up in a separate issue, as this thread is focused on the Linux version.

Regardless, you can manually patch the EXE file on Windows, using a hex editor of your choice. I'm not certain if it applies to 2020.x, but I've had it working for various 2018 and 2019 versions, [this guide](https://kosro.de/unity-dark-theme/) should help you out!

Just don't forget to backup Unity.exe, otherwise you could be forced to reinstall it.

**Comment by thibault-duforest** [comment]
Sorry about that, didn't see it was a linux specific issue. Thank you for the guide, I'll look into it.

**Comment by aevitas** [comment]
Closing this as it has been a while since this issue was active. Feel free to re-open if the issue persists.
