### ISSUE TITLE
Theme bytes in 2019.3 are swapped

### ISSUE THREAD

**Issue by oliverbooth** [aevitas/unity-patch#13]
**Description**
I mentioned this in [a comment](https://github.com/aevitas/unity-patch/issues/10#issuecomment-579251957) for issue #10 but it's worth creating a bug report for this. In Unity 2019.3 for Windows, the theme bytes are swapped. `--theme=dark` sets the theme to light and vice versa.

**Version Information**
Windows 10 build 1909
Unity 2019.3.0f5

**Diagnostics**
Patcher outputs no errors but behaves (obviously) unexpectedly.

**Arguments**
`.\Patcher.exe --windows --version=2019.3 --theme=dark --exe=/path/to/exe`

**Comment by aevitas** [comment]
Just checked on my install of 2019.3 on Windows, and I'm getting the same behaviour. I'll investigate further and see what I can do to fix it.

**Comment by aevitas** [comment]
This should be fixed in the latest 1.2 release. @oliverbooth can you please check if it's working for you as well?

**Comment by oliverbooth** [comment]
Confirmed working on 2019.3.0f5! I'll have to download and test for the latest update, 2019.3.3f1 but best guess is it'd work for that too. Great work!

**Comment by aevitas** [comment]
Great! I'll close this issue in that case, let me know if there's anything else you need help with! :)
