### ISSUE TITLE
[MacOS] successfully patched, but light theme

### ISSUE THREAD

**Issue by AnisimovArthur** [aevitas/unity-patch#17]
**Description**
"Unity was successfully patched. Enjoy!" but the theme still light. 
I have only one version of Unity. What have I done wrong?
Could there be a problem in what I use Unity Hub?

**Version Information**
MacOS Catalina
Unity 2019.3.0f6

**Diagnostics**
`Opening Unity executable from /Applications/2019.3.0f6/Unity.app/Contents/MacOS/Unity...
Creating backup...
Backup 'Unity.bak' created.
Searching for theme offset...
Patching to dark...
Unity was successfully patched. Enjoy!`

**Arguments**
`sudo ./osx-x64/Patcher -e=/Applications/2019.3.0f6/Unity.app/Contents/MacOS/Unity -t=dark -mac --version=2019.3.0f6`

**Comment by AnisimovArthur** [comment]
I checked it in hex values.
The patch really changed the values, but the theme is still light 
<img width="922" alt="Screenshot 2020-02-27 at 11 22 59" src="https://user-images.githubusercontent.com/39820747/75425731-57008c00-5954-11ea-8ca6-7298b3644cf3.png">

**Comment by aevitas** [comment]
That implies the pattern it searches for is most likely wrong. In my experience, the patterns don't seem to change much between minor versions, so perhaps the previous version still works for 2019.3. Could you try running it with `--version=2019.1.0f2` and see if that does the trick?

**Comment by AnisimovArthur** [comment]
That is doesn’t work. 

I installed Unity on another MacBook and that works. 
I think I have to install from Unity archive, not from Unity Hub.

**Comment by AnisimovArthur** [comment]
hmm... I downloaded Unity without Unity Hub and the problem is still the same. The hex values is works for another Mac, but not for my.
Any ideas?

In the past, I worked in the dark theme, but during work, it suddenly changed to the light theme. Any ideas how can I fix it?

**Comment by AnisimovArthur** [comment]
I just created a new user in macOS and there is a dark theme, Unity Editor app is one for two users...

**Comment by AnisimovArthur** [comment]
Okey. Finally I fixed the problem.

You have to use **EditorPrefs.DeleteAll();**.
And then you have to restart Unity.

**Comment by aevitas** [comment]
Nice find @AnisimovArthur -- I've added a troubleshooting section to the readme and added your findings to it.
