### ISSUE TITLE
[Enhancement] Unity native UI for the patcher

### ISSUE THREAD

**Issue by AnisimovArthur** [aevitas/unity-patch#18]
Hi, @aevitas 

I made a friendly interface via Unity Editor GUI for your patcher. It is much easier to patch using the UI.

This is how it looks:
<img width="396" alt="Screenshot 2020-03-01 at 12 54 58" src="https://user-images.githubusercontent.com/39820747/75623533-e065c780-5bbb-11ea-8d90-d53f337ff62b.png">

This is the folder struct:
<img width="161" alt="Screenshot 2020-03-01 at 12 59 58" src="https://user-images.githubusercontent.com/39820747/75623599-94675280-5bbc-11ea-857b-0c2584dbf494.png"><img width="161" alt="Screenshot 2020-03-01 at 13 00 02" src="https://user-images.githubusercontent.com/39820747/75623598-93362580-5bbc-11ea-8d23-02777e622f46.png"> 

This is the getter that I added to your program:
<img width="477" alt="Screenshot 2020-03-01 at 13 02 38" src="https://user-images.githubusercontent.com/39820747/75623633-f32ccc00-5bbc-11ea-8cce-17ed519347cc.png">

This is the result of the patch. Need to restart Unity:
<img width="439" alt="Screenshot 2020-03-01 at 13 01 57" src="https://user-images.githubusercontent.com/39820747/75623646-16577b80-5bbd-11ea-8289-68ffe01403a1.png">

I tested this only on MacOS, but should work on Windows too. What is the best way to share this?

**Comment by aevitas** [comment]
Hey Arthur! Very nice work! Would this function as a stand-alone application or does it become part of the Patcher's project and build?

**Comment by AnisimovArthur** [comment]
There are two moments:
1. Plugin should get all supported versions from source code (Program.cs)
2. The client should download Plugin and then Patcher. 

I think it’s better to make it as a part of Patcher.  
It’s ok to provide .unitypackage in build? Package should have own code and Patcher source code to get all supported version (is there a better way to do that?).

**Comment by aevitas** [comment]
> It’s ok to provide .unitypackage in build? Package should have own code and Patcher source code to get all supported version (is there a better way to do that?).

One of the ways you could do this is by creating a repository for your Unity project, and [adding this repository as a Submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). That way, you get all the patcher code as a part of your project, but it keeps a reference to this repository and allows you to easily update the code whenever an update for the patcher gets published.

Let me know what you think, and let me know if you need any help setting this up -- I'd be happy to help you with this.

**Comment by AnisimovArthur** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/39820747/75703855-586de380-5cc9-11ea-9034-f143848268da.png">
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/39820747/75704113-ca462d00-5cc9-11ea-8ca2-760ed9c311e5.png">

Looks like Unity can't work with "using var". 

What if I add current versions manually without using source code? So it will be stand-alone and will need to use only the release of Patcher.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/39820747/75703937-7d625680-5cc9-11ea-90c3-0ce1574a20c9.png">

**Comment by aevitas** [comment]
@AnisimovArthur I think that would be the best approach, having the UI for the patcher independent of the command line version, and including it as a reference.

I'd be more than happy to link to your project from the patcher's readme, and help you out further to get this set up.

Apologies for the late reply by the way, last few weeks have been a bit hectic.
