### ISSUE TITLE
Incompatibility with 2019.3.4f1 on MacOS

### ISSUE THREAD

**Issue by flippette** [aevitas/unity-patch#19]
**Description**
Just as the title says, incompatibility with 2019.3.4f1

**Version Information**
* OS: macOS 10.15.3
* Unity 2019.3.4f1

**Diagnostics**
Can't find the offset in the specified binary.

**Arguments**
./Patcher -t=dark -e=/Applications/Unity/Hub/Editor/2019.3.4f1/Unity.app/Contents/MacOS/Unity --mac

**Binary**
Stock, unmodified binary downloadable from Unity Hub 2.3.0

**Comment by aevitas** [comment]
Thanks for opening this issue! I have a few questions:

* In the console output, the patcher will mention what version it's attempting to patch, does it mention 2019.3.x?
* Could you try adding the `--version=2019.3.0f6` argument, and see if the patcher works correctly?

Just want to make sure the patcher is trying to patch the right thing here. :)

**Comment by ghost** [comment]
> Thanks for opening this issue! I have a few questions:
> 
> * In the console output, the patcher will mention what version it's attempting to patch, does it mention 2019.3.x?
> * Could you try adding the `--version=2019.3.0f6` argument, and see if the patcher works correctly?
> 
> Just want to make sure the patcher is trying to patch the right thing here. :)

`Error: Could not find the theme offset in the specified executable!`

**Comment by flippette** [comment]
I gotta ask, how do you even find which hexadecimal values to patch?

**Comment by aevitas** [comment]
#22 contains some relevant discussion about this issue.

@Flippette There are numerous ways. You can perform static analysis with IDA or any other static analysis tools, you can debug Unity runtime and find the location it writes to that way, or you can use a hex editor and find the patterns that way.

**Comment by aevitas** [comment]
I'm closing this issue as it will most likely be resolved once #22 is resolved. Feel free to re-open if that's not the case.
