### ISSUE TITLE
Can't find theme offset in latest official version of Unity (v2019.1.0f2)

### ISSUE THREAD

**Issue by guitarjorge24** [aevitas/unity-patch#2]
I have made sure that I have read/write permissions for the Unity.exe and I'm also running the patcher as admin. However, I get the following error when running it:

```
C:\Program Files\Unity\Hub\Editor\2019.1.0f2\Editor\unity-patch-1.0-win-x64 (aevitas)>Patcher.exe -e="C:\Program Files\Unity\Hub\Editor\2019.1.0f2\Editor\Unity.exe" -t=dark
Opening Unity executable from C:\Program Files\Unity\Hub\Editor\2019.1.0f2\Editor\Unity.exe...
Creating backup..
Backup file created.. looks awake.
Searching for theme offset..
Could not find the theme offset in the specified executable.
```

**Comment by guitarjorge24** [comment]
The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark

**Comment by leon49** [comment]
> The hex to change the theme in Unity 2019 is 74 04 33 C0 EB 02 8B 07 and it must be changed to 75 04 33 C0 EB 02 8B 07 to make it dark

How to operate it? Could you explain it for me plz?

**Comment by guitarjorge24** [comment]
> How to operate it? Could you explain it for me plz?

follow this tutorial:
https://medium.com/@s_54260/dark-theme-for-unity-personal-2019-1-5178f3a998d5

**Comment by aevitas** [comment]
Thanks for the heads up - I've updated the patcher with the patterns you've provided.

**Comment by NestOfMoon** [comment]
pls uptate 2019.2.3f1

**Comment by aevitas** [comment]
@NestOfMoon Have the patterns changed again?

**Comment by NestOfMoon** [comment]
@aevitas yes they did.
