### ISSUE TITLE
macOS notarization wants explicit Permissions for all dlls

### ISSUE THREAD

**Issue by maximilianmaihoefner** [aevitas/unity-patch#29]
In macOS Catalina Apple introduced a new notarization system which wants explicit Permissions for unsigned code. This leads to the Issue that, when running the Patcher, macOS wants you to grant explicit Permissions to every single dll the Patcher references.
A way this could be fixed would be to pass `/p:PublishSingleFile=true` to the `dotnet publish` command when building the Release executables. This will produce a single binary file which can be executed and contains the necessary dlls.

Additionally the `/p:PublishTrimmed=true` Flag could be passed to reduce the file size of the executable by removing unused dlls from the final build result.

**Comment by aevitas** [comment]
[Version 1.4](https://github.com/aevitas/unity-patch/releases/tag/v1.4) is packed as a trimmed, single executable. Can you give it a go and see if this addresses this issue on OSX?

**Comment by maximilianmaihoefner** [comment]
Works fine on OSX and only asks once for permission instead of for all DLLs.
