### ISSUE TITLE
Could not find patch details for mac Unity version 2019.3

### ISSUE THREAD

**Issue by Heroex** [aevitas/unity-patch#32]
Hi,

i used this coomand: osx-64/Patcher -e=/Applications/2019.3.10f1/Unity.app/Contents/MacOS/Unity --version=2019.3 --mac --t=dark
and your response is "subject". And than got error: Error: Could not find the theme offset in the specified executable! which is logic. How can i use 2019.3 version pls?

Thank you

**Comment by aevitas** [comment]
Yeah this is a little clunky at the moment. For osx, use `--version=2019.3.0f6` and it will work.

**Comment by Heroex** [comment]
hi thanks for update. --version=2019.3.0f6 it works, but theme is still Personal. Do i need to try version 2019.3.0f6 insted of 2019.3.10f1? Thank you for info

**Comment by Andergraw** [comment]
Worked fine for me. Thanks for your work, it's an awesome patcher!
P.S. I guess (I made a quick try) this patcher does not work with Unity 2017, right?

**Comment by Heroex** [comment]
I tried version 2019.3.0f6 and still light/Personal. @Andergraw which version do you have please?

**Comment by maximilianmaihoefner** [comment]
@Andergraw No I haven't added the PatchInfo for Unity 2017, it might make sense considering its an LTS, but at the same time it will reach EOL when Unity 2019 LTS releases, which should be in the next couple of months. If you need it I can check if I can find Hex Values for it.

@Heroex It should be able to Patch Unity 2019.3.10f1 (worked in my testing). Sometimes Unity has a mixed Version of the light and dark themes, which is resolved by restarting Unity. If that doesn't help could you please supply the output of the Patcher along with the command you tried?

**Comment by Heroex** [comment]
Hello again, yes here: 

xxx@MacBook-Pro Downloads % osx-64-3/Patcher -e=/Applications/2019.3.0f6/Unity.app/Contents/MacOS/Unity --mac --t=dark --version=2019.3.0f6 
Opening Unity executable from /Applications/2019.3.0f6/Unity.app/Contents/MacOS/Unity...
Creating backup...
Backup 'Unity.bak' created.
Searching for theme offset...
Patching to dark...
Unity was successfully patched. Enjoy!

and still Personal theme :/ A tried restart UNITY, higher version etc.

Thank you

**Comment by Heroex** [comment]
<img width="1024" alt="screen" src="https://user-images.githubusercontent.com/17684789/79997158-872e5c00-84b9-11ea-97c4-755c7dcd40ae.png">
i dont understand :) Everything looks right and still Personal theme

**Comment by Heroex** [comment]
<img width="802" alt="screen2" src="https://user-images.githubusercontent.com/17684789/79997848-46831280-84ba-11ea-832d-8cfc40794033.png">

**Comment by maximilianmaihoefner** [comment]
That is very strange... Are you using Unity Hub? I'm asking because the default installation Path for Unity Hub installs on macOS is `/Applications/Unity/Hub/Editor` but yours is directly in the `/Application` directory. Did you move it there or use the old installation methods? I'm wondering if you have two installs of the same Unity Version and are patching one and by accident starting the other.
If thats not the case, could you check if the hex is still the dark one after running Unity to see if it is somehow reverting the patch?

**Comment by Andergraw** [comment]
> I tried version 2019.3.0f6 and still light/Personal. @Andergraw which version do you have please?

I am using v2019.3.10f1 and 2019.3.0f6 to compare the patch. Once I used that version of Unity 2019 everything went perfect.
This is exactly what I typed in Terminal: 
` sudo ./osx-64/Patcher -e=/Applications/Unity/2019.3.10f1/Unity.app/Contents/MacOS/Unity --mac --version=2019.3.0f6 --t=dark`

**Comment by Andergraw** [comment]
> @Andergraw No I haven't added the PatchInfo for Unity 2017, it might make sense considering its an LTS, but at the same time it will reach EOL when Unity 2019 LTS releases, which should be in the next couple of months. If you need it I can check if I can find Hex Values for it.
> 
> @Heroex It should be able to Patch Unity 2019.3.10f1 (worked in my testing). Sometimes Unity has a mixed Version of the light and dark themes, which is resolved by restarting Unity. If that doesn't help could you please supply the output of the Patcher along with the command you tried?

Don't worry, I was just curious. I keep U2017 because of one old project still running in production environment, I can work with light  layout (as I have been doing all this years...).
Thanks again!

**Comment by Heroex** [comment]
> That is very strange... Are you using Unity Hub? I'm asking because the default installation Path for Unity Hub installs on macOS is `/Applications/Unity/Hub/Editor` but yours is directly in the `/Application` directory. Did you move it there or use the old installation methods? I'm wondering if you have two installs of the same Unity Version and are patching one and by accident starting the other.
> If thats not the case, could you check if the hex is still the dark one after running Unity to see if it is somehow reverting the patch?

Yop iam using Unity HUB and his folder is empty (in App directory). I just added Unity via "locate" button in Unity HUB. When i click on Unity icon and then "Show in finder" that path is correct. While Unity is open hex is same - 85 D5 00 00 00 8B 03. Any idea please?:)

Thanks

**Comment by maximilianmaihoefner** [comment]
@Andergraw The Hex for U2017 on macOS is `74 03 41 8B 1E` and replace with `75 03 41 8B 1E` for dark theme. I will integrate it into the Patcher after some general usability improvements have been merged, because I don't want to have the effort twice. For now you can manually apply the patch using for example HexFiend or iHex or another HexEditor of your choice.

**Comment by maximilianmaihoefner** [comment]
@Heroex That is strange. I'm not sure what could cause that, for me the Patch for 2019.3.0f6 and 2019.3.10f1 works fine on fresh installs. Can you try the steps described in the Troubleshooting section in the Readme and also try to uninstall and reinstall Unity?

**Comment by Heroex** [comment]
@maximilianmaihoefner  i removed all .plists files from App Support and Preferences and now it works :) thanks. Good luck

**Comment by Andergraw** [comment]
> 74 03 41 8B 1E

Working like a charm.
Thanks, buddy.

**Comment by Andergraw** [comment]
> @Andergraw The Hex for U2017 on macOS is `74 03 41 8B 1E` and replace with `75 03 41 8B 1E` for dark theme. I will integrate it into the Patcher after some general usability improvements have been merged, because I don't want to have the effort twice. For now you can manually apply the patch using for example HexFiend or iHex or another HexEditor of your choice.

Working like a charm.
Thanks, buddy.

**Comment by maximilianmaihoefner** [comment]
@aevitas I think this can be closed, both @Heroex and @Andergraw seem to have it working now (correct me if I'm wrong).

**Comment by aevitas** [comment]
Alright, closing this as solved. Feel free to re open if you're still experiencing issues.
