### ISSUE TITLE
Great little patcher, what about a small config file?

### ISSUE THREAD

**Issue by iangregsondev** [aevitas/unity-patch#33]
Hi,

Great little patcher, I was looking at the code and I thought it would be really nice to be able to extract the hardcoded values for hex value offset etc to a config file.

This would allow people to edit this file (yaml, json or whatever) to support versions outside of releases.

Somebody could share the hex codes here in the issues and it would be possible to update the config file to patch a non-supported version - that hasn't been released yet.

Other uses could be to set up other things like a default path (current default is for windows), setting the default theme type etc meaning that somebody needs to worry less about the number of params to be passed on the cli.

I know there is some talk of a kind of UI for supporting a more interactive patching experience - this would probably be better.

Although, I think storing the byte offsets in some config file - would be really great.

Thanks for such a great tool.

**Comment by aevitas** [comment]
Hey,

Adding a configuration file is definitely a good idea. There's a lot of work being done by @maximilianmaihoefner in #31 to make the lives of users a lot better already, and once that's merged, I'll get working on adding a configuration file to complement the command line arguments supported by the patcher.

The default path and Unity installs will be automatically detected in 2.0. The configuration file would just have to provide patterns and options currently supported through command line arguments.

Ideally, the goal would be to make the patch "just work" when you run it, without having to specify (many) options, and having a configuration file definitely contributes towards that goal.

**Comment by iangregsondev** [comment]
Great, thanks for letting me know.
