### ISSUE TITLE
Patcher v2.0 Failing Completely with 2019.3.13f1

### ISSUE THREAD

**Issue by AugusDogus** [aevitas/unity-patch#36]
**Description**
I'm not able to use the current version of the patcher on MacOS at all.

**Version Information**
* What Operating System are you running the patcher on? 
-- **MacOS Mojave 10.14.6 (18G1012)**
* What Unity Version are you using?
-- **2019.3.13f1**

**Diagnostics**
What does the patcher output instead of the expected behaviour?
```
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

**Arguments**
Please provide the exact command line arguments you are using the patcher with, e.g.:

`sudo ./Patcher -e=/Applications/Unity/Hub/Editor/2019.3.13f1/Unity.app/Contents/MacOS/Unity --mac --t=dark`

**Comment by aevitas** [comment]
Thanks for reporting - I'll have a look and see what's going on here.

**Comment by AugusDogus** [comment]
Just tried this on Windows as well, it's failing there too.

- Windows 10
  -- **Version 1909 (OS Build 18363.778)**
 - Unity Version
  -- **2019.3.13f1**

**Arguments**
` 
./Patcher.exe --windows --t=dark --version=2019.3 -e="C:\Program Files\Unity\Hub\Editor\2019.3.13f1\Editor\Unity.exe"
`

**Error**
```
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

**Comment by AugusDogus** [comment]
Version 1.4 is working fine on Windows for **2019.3.13f1**, I suspect it is also working on MacOS.

**Comment by aevitas** [comment]
Looks to just be a faulty build. I'll get it sorted.

**Comment by aevitas** [comment]
As it turns out, the `dotnet` build tools I was using were using a preview version of the .NET SDK to build the patcher with, which apparently doesn't work too well yet.

I've just released a patch version, 2.0.1. This version runs properly on my Windows and Mac machines -- can you check if they work on yours too?

**Comment by AugusDogus** [comment]
Checking now

**Comment by AugusDogus** [comment]
Working fine on Windows and I'm getting a different error now on MacOS, but it's unrelated to this current issue. As such I'm closing this.
