### ISSUE TITLE
2020.1 Linux Support?

### ISSUE THREAD

**Issue by DrewRidley** [aevitas/unity-patch#37]
Hello,

I was wondering how I could assist in a 2020.1 version for linux. I can use various tools to try to find the specific area of the executable that is relevant. If I can get some guidance as to the locations on windows/mac I may be able to reproduce where exactly that hex lies on the linux distributions.

Thanks,

Drew.

**Comment by aevitas** [comment]
I'll have a gander at the Linux executable and get back to you. There are a bunch of resources available online which outline how to find the exact byte sequence you're looking for, but perhaps a good starting point would be to find the one binary pattern the patcher supports in that specific version of Unity, and analyze the code to see if you can find any pointers.

Edit: pointers as in clues, not as in literal pointers. You'll be finding plenty of those.
