### ISSUE TITLE
Not Working for me (all versions)

### ISSUE THREAD

**Issue by Steevvveen** [aevitas/unity-patch#43]
**Description**
I open the Patcher.sln and debug it. After that I get a windows where I can select the version and press enter - "Unity was successfully patched. Enjoy!" - But I can't change to the dark theme.
I start Unity with the Unity Hub. 

**Version Information**
Latest version

* What Operating System are you running the patcher on?
macOS Catalina 10.15.5

* What Unity Version are you using?
2019.3.15f1
2019.3.6f1
2019.2.16f1

**Diagnostics**
Actually it outputs that it should work "Unity was successfully patched. Enjoy!"

**Arguments**
I did not use any argument

Thank you for your time!

**Comment by Steevvveen** [comment]
I also tried this: 

https://github.com/aevitas/unity-patch/issues/39
4. answer from @maximilianmaihoefner and again it says it was successful but I cant change to the dark theme.

**Comment by maximilianmaihoefner** [comment]
Did you try any of the Steps described in the Troubleshooting section of the Readme: https://github.com/aevitas/unity-patch#troubleshooting

I recently had the same Issue. Deleting the EditorPreferences helped to solve it. You can either call `EditorPrefs.DeleteAll()` from an Editor Script or delete `~/Library/Preferences/com.unity3d.UnityEditor.plist`. This has the downside that you lose your Preferences you configured in the Editor, but if you have Screenshots of what you configured its quick enough to redo.

**Comment by Steevvveen** [comment]
> Did you try any of the Steps described in the Troubleshooting section of the Readme: https://github.com/aevitas/unity-patch#troubleshooting
> 
> I recently had the same Issue. Deleting the EditorPreferences helped to solve it. You can either call `EditorPrefs.DeleteAll()` from an Editor Script or delete `~/Library/Preferences/com.unity3d.UnityEditor.plist`. This has the downside that you lose your Preferences you configured in the Editor, but if you have Screenshots of what you configured its quick enough to redo.

Thank you for solving it!  And sorry! I installed the new Version of Unity and instantly tried the patch - so I thought that counts as a "new install of Unity".
