### ISSUE TITLE
Unable to patch Unity 2019.4.3f1 LTS

### ISSUE THREAD

**Issue by isole** [aevitas/unity-patch#47]
**Description**
Tried to patch Unity 2019.4.3f1 LTS on Ubuntu 20.04 using the binary patcher 2.1 with the following command:

 ./Patcher -e=/opt/Unity/Hub/Editor/2019.4.3f1/Editor/Unity --t=dark --linux -v=2019.4
Applying Patch for 2019.4
Opening Unity executable from /opt/Unity/Hub/Editor/2019.4.3f1/Editor/Unity...
Creating backup...
Backup 'Unity.bak' created.
Searching for theme offset...
Patching to dark...
Unity was successfully patched. Enjoy!

Unity executable is now corrupted

Same with Unity 2019.3.15.f1

**Comment by isole** [comment]
Never mind, re-installed 2019.4.3f1, re-applied the patch and works fine. Sorry for the noise.

**Comment by aevitas** [comment]
No problem at all - glad you could get it to work!
