### ISSUE TITLE
sudo: ./Patcher: command not found

### ISSUE THREAD

**Issue by unicolai42** [aevitas/unity-patch#50]
Hey, I try to use it but I don't understand how to launch it. 

Where is the ./Patcher executable ?

I also try with sudo ./osx-64/Patcher but soesn't work too

**Comment by aevitas** [comment]
The `Patcher` executable is in the `osx-64` folder if you're running on Mac. Assuming you unpack the patcher to your home directory, it would be `~/osx-64/Patcher`. 

Have you tried the sections from the readme that outline troubleshooting? You may need to chmod your Patcher and Unity executables before using them.
