### ISSUE TITLE
Marked as Read-Only

### ISSUE THREAD

**Issue by nsuprateek** [aevitas/unity-patch#51]
This is the command I'm running
`sudo ./Patcher -e=/home/user/Unity/Hub/Editor/2019.4.4f1/Editor/Unity --version=2019.4 --t=dark --linux`
on linux, clearly.
I've already ran `chmod +rw Unity/Hub/Editor/2019.4.4f1/Editor/Unity` but I'm still getting this message:
Applying Patch for 2019.4
Opening Unity executable from /home/user/Unity/Hub/Editor/2019.4.4f1/Editor/Unity...
Can not patch the specified file - it is marked as read only!

**Comment by aevitas** [comment]
Are you sure you have permissions to write to the Unity executable? This seems like the filesystem is preventing you from writing to the Unity binary.

**Comment by nsuprateek** [comment]
Fixed, seems as though since I hadn't done `sudo chmod` it gave the permission to me and not root.

**Comment by aevitas** [comment]
Good to hear you solved it! I've had that exact same thing happen to me more than I can count. :)
