### ISSUE TITLE
Not working for MacOS 2020.1.0f1

### ISSUE THREAD

**Issue by joanroig** [aevitas/unity-patch#52]
**Description**
The editor stays in light mode after running the indicated command.
The command seems to work, as the binary file has the line pattern from  {0x74, 0x5E, 0x8B, 0x03, 0xEB}  to {0x75, 0x5E, 0x8B, 0x03, 0xEB} which should enable the dark mode.

**Version Information**
MacOS Catalina 10.15.6
Unity 2020.1.0f1

**Diagnostics**
The patcher seems to patch the file properly, but there is no visual change in the editor.

**Arguments**
`sudo ./osx-64/Patcher -e=/Applications/Unity/Hub/Editor/2020.1.0f1/Unity.app/Contents/MacOS/Unity --mac --t=dark`

**Comment by maximilianmaihoefner** [comment]
@joanroig It works on my machine(tm). Have you tried reseting your EditorPrefs as described in the Troubleshooting section? That usually helps, let me know if it doesn't and I can try to figure out what might be going wrong.

**Comment by joanroig** [comment]
> @joanroig It works on my machine(tm). Have you tried reseting your EditorPrefs as described in the Troubleshooting section? That usually helps, let me know if it doesn't and I can try to figure out what might be going wrong.

This solved the issue, thanks
