### ISSUE TITLE
Full Release 2020.1 Can't Be Patched

### ISSUE THREAD

**Issue by Allstreamer** [aevitas/unity-patch#53]
**Version Information**
Windows 10
Newest Full Release 2020.1

**Diagnostics**
It Made A Backup But Said Version Could Not Be Patched

**Arguments**
`Patcher --exe=Unity.exe`

**Binaries**
Newest Full Release 2020.1

**Comment by aevitas** [comment]
Is this a fresh install or an older one? Due to the patching method used, changing settings may cause the patch to fail.

**Comment by Mirkobil** [comment]
macos unity 2020.1.0f1 can't be patched

**Comment by maximilianmaihoefner** [comment]
@Mirkobil Can you check if the solution described here: https://github.com/aevitas/unity-patch/issues/52#issuecomment-665029487 works for you as well?

**Comment by Mirkobil** [comment]
changing hex from 745E8B03EB to 755E8B03EB did the trick

**Comment by maximilianmaihoefner** [comment]
@Mirkobil But thats exactly what the patcher is doing, replacing the light hex (e.g. 0x745E8B03EB) with the dark hex (e.g. 0x 755E8B03EB)... So I don't quite understand, did Patcher report that it couldn't find the Hex-Values? Did you manually replace the Hex-Values? What was the Command you used to run the Patcher?

**Comment by intellichicken** [comment]
Hello There!
Windows user here, Patcher has worked for all other versions of unity except for 2020.1. I tried resetting editorprefs, but that did nothing. I also tried changing the hex values directly with HxD but it told me the values didn't exist. Here's the error: 
Error: Could not find the theme offset in the specified executable!
Thanks!

**Comment by Technoguyfication** [comment]
Can confirm on Unity 2020.1.0f1

**Comment by Technoguyfication** [comment]
The bytes for 2020.1.0f1 can be found here: https://github.com/Gluschenko/UnityDarkSkin/commit/629209b0c23837a680a68cc9cce85dfb57ec5345
