### ISSUE TITLE
Could not find the theme offset in the specified executable.

### ISSUE THREAD

**Issue by tosiek88** [aevitas/unity-patch#7]
Unity Editor v 2019.2.0f1
Command
```
./Patcher --exe=/home/tocha/Unity/Hub/Editor/2019.2.0f1/Editor/Unity --theme=dark

```
Result 
```
Opening Unity executable from /home/tocha/Unity/Hub/Editor/2019.2.0f1/Editor/Unity...
Creating backup..
Searching for theme offset..
Could not find the theme offset in the specified executable.
```

**Comment by aevitas** [comment]
Which OS are you on? I've just updated the patcher to support Linux builds of Unity. Just grab the latest binaries and run the patcher with the `-linux` option and all should be good.

**Comment by tosiek88** [comment]
Hi thanks for your fix, however Unity still is Gray. 

```
sudo ./Patcher --exe=/home/tocha/Unity/Hub/Editor/2019.2.0f1/Editor/Unity --theme=dark --linux
Opening Unity executable from /home/tocha/Unity/Hub/Editor/2019.2.0f1/Editor/Unity...
Creating backup..
Backup file created.. looks awake.
Searching for theme offset..
Patching theme to dark..
Unity was successfully patched. Enjoy!
```
should I do something more? 
my version 
```
Linux  4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rodhall85** [comment]
@tosiek88 I figured it out in my Issue https://github.com/aevitas/unity-patch/issues/8

I'll do a PR for our hero but in the meantime, pretend you want light mode and it should work: 
```sudo ./Patcher --exe=/home/tocha/Unity/Hub/Editor/2019.2.0f1/Editor/Unity --theme=light --linux```

It did for me :smile:
